site_name: Documentación
repo_url: https://github.com/adrianb30/GranaWeb
repo_name: Github
nav:
    - Inicio: 'index.md'
    - Instalación: './instalacion.md'
    # - Rafael Romera: './rafa_romera/index.md'
    # - Kubernetes: './kubernetes/index.md'
theme:
    name: mkdocs
    lenguage: es
    locale: es
    include_sidebar: false
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.tabs.sections
    palette: 
      - scheme: default
        primary: blue
        accent: blue
        toggle:
          icon: material/weather-sunny 
          name: Cambiar al modo oscuro
      - scheme: slate
        toggle:
          icon: material/weather-night
          name: Cambiar al modo claro
    font:
      code: Source Code Pro
